@extends('layouts.master') 
@section('content')
    @include('partials.navbar')
    <main>
        @include('hero')
        @include('partials.categories')
        @include('partials.featuredProducts')
        @include('partials.newsletter')
    </main>
    @include('partials.footer')
@endsection